[package]
name = "sync"
description = "Mailbox synchronization engine for Tegami"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
mail-core = { path = "../mail-core" }
mail-mime = { path = "../mail-mime" }
store = { path = "../store" }
tokio = { version = "1", features = ["fs"] }

[dev-dependencies]
tempfile = "3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
