[package]
name = "imap"
description = "async-imap MailBackend implementation for Tegami"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
async-imap = { version = "0.11.3", default-features = false, features = ["runtime-tokio"] }
futures-util = "0.3"
mail-core = { path = "../mail-core" }
rustls = "0.23"
rustls-native-certs = "0.8"
tokio = { version = "1", features = ["net", "io-util", "time"] }
tokio-rustls = "0.26"

[dev-dependencies]
accounts = { path = "../accounts" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
zbus = { version = "5", default-features = false, features = ["tokio"] }